name: Prepare pull request for release

run-name: pr-for-release

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
    - name: Run updater
      run: python update.py
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: create new release
        branch: update
        delete-branch: true
        title: 'Create new release'
        assignees: dynobo
        reviewers: dynobo
